# Generated by Django 4.1.4 on 2023-02-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="poultryform",
            fields=[
                ("S_no", models.IntegerField(primary_key=True, serialize=False)),
                ("Big_chiken", models.IntegerField()),
                ("small_chiken", models.IntegerField()),
                ("total_cost", models.IntegerField()),
            ],
        ),
    ]
